# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SOPT-29th-JointSeminar-9-Client-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SOPT-29th-JointSeminar-9-Client-iOS
  pod 'Alamofire', '~> 5.4.3'
  pod 'Moya', '~> 15.0.0'
  pod 'SnapKit', '~> 5.0.1'
  pod 'Then', '~> 2.7.0'
end
